# Generated by Django 3.1.1 on 2020-10-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo del Producto')),
                ('descripcion', models.TextField(verbose_name='Detalle del Producto')),
                ('imagen', models.URLField(verbose_name='Url de la imagen')),
                ('precio', models.IntegerField(verbose_name='Precio del Producto')),
                ('estaEnOferta', models.BooleanField(default=False, verbose_name='Esta en oferta?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
        ),
    ]
