# Generated by Django 3.1.1 on 2020-11-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20201029_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='titulo',
            field=models.CharField(max_length=5, verbose_name='Titulo del Producto'),
        ),
    ]
